name: Using Github Action

on: [push]

jobs:
  use-ai:
    runs-on: ubuntu-latest
    name: Using Github Action
    steps:
      - uses: actions/checkout@v4
      - id: ai
        uses: bitestream/ai@v1  #use marketplace
        # uses: ./ # test locally
        with:
          engineer: 'Someone else'
      - run: echo random-number ${{ steps.ai.outputs.random-number }}
        shell: bash
